blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/iracic82/terraform-github-actions-starter/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/iracic82/terraform-github-actions-starter/security/policy
    about: Report security vulnerabilities privately
